@isTest
public with sharing class AccountController {
   /* public AccountController() {

    }

    @AuraEnabled(cacheable=true)
    public static List<Account> getAccountList() {
        return [
            SELECT Id, Name, PersonEmail
            FROM Account
            WHERE IsPersonAccount = true
            LIMIT 50
        ];
    }*/
    //This is my change for Ticket Xyz
    //This is achanbge as part of some ticket WME-xyz

}