@isTest
public class MockAdapterTest {
 /* @isTest
    static void testProcessRequestMockCapture() {
      Test.startTest();
        commercepayments.PaymentGatewayContext context = new commercepayments.PaymentGatewayContext(null, null);
        MockAdapter adapter = new MockAdapter();
        Test.setMock(HttpCalloutMock.class, new AurusMockHttpResponse());
        commercepayments.GatewayResponse response = adapter.processRequest(context);
        System.assertNotEquals(null, response);
        Test.stopTest();
    }*/
}