@isTest
public class WM_CallFlowQueueableTest {
/*

    @isTest
    static void testMethod1(){
        String inputVariablesJSON;
  		String flowApiName;
        String namespace;
        Test.startTest();
            if(String.isEmpty(namespace)) {
                System.enqueueJob(new WM_CallFlowQueueable(inputVariablesJSON,flowApiName));
            } else {
                System.enqueueJob(new WM_CallFlowQueueable(inputVariablesJSON,flowApiName,namespace));
            }
        Test.stopTest();
   
    }
*/

}