/*Author : schauhan@liveareacx.com
* Class : WMConstants
* Purpose : Maintaining the constant values in form of variables
* Date : 4th Jan'2021
* @last modified on  : 01-12-2021
* @last modified by  : npedyala@liveareacx.com
* */

public class WMConstants {
    
    public static String FirstName = 'John';
    public static String LastName = 'Doe';
    public static String Country = 'United States';
    public static String City = 'New York';
    public static String PostalCode = '58100';
    public static String  State= 'New York';
    public static String CardType = 'Visa';
    public static String Status = 'Active';
    public static String ProcessingMode = 'External';
    public static String EmptyString = '';
    public static String CaptureTransactionType = '05';
    public static String AuthorizationTransactionType = '04';
    public static String RefundTransactionType = '02';
    public static String VoidTransactionType = '06';
    public static String ProcessingMode1 = '0';
    public static String CorpID = '22605';
    public static String LanguageIndicator = '00';
    public static String CurrencyCode = '840';
    public static String PostAuthCount = '00';
    public static String OrigTransactionIdentifier = 'oti';
    public static String AurusPayTicketNum = '000000000000000000';
    public static String StoreId = '17001';
    public static String MerchantIdentifier = '100000077762';
    public static String TerminalId = '24452320';
    public static Decimal Amount = 100;
    public static String GatewayRefNumber = '123';
	public static String GatewayRefDetails = '123';
    public static integer  ExpiryMonth = 10;
    public static integer  ExpiryYear = 2024;
    public static string   Phone = '3333333333';
    public static string  Email = 'Naveen@test.com';
    public static string  Description = 'Description';
    public static string  Name = 'First Middle Last';
    public static Integer Quantity = 02;
    public static decimal UnitPrice = 200;
    public static decimal TotalLineTaxAmount = 500;
    public static decimal TotalTaxAmount = 100;
    public static decimal TotalLineAmount = 200;
    public static Integer OrderItemNumber = 02;
    public static Integer TypeCode = 02;
    public static string  ProductCode = '0123';
    public static string  QuantityUnitOfMeasure = 'Each';
    public static string  PaymentGatewayName = 'WM_PaymentGatewayAdapter';
    
}