@isTest
public class WrapperClass{

    /*public class Errors {
    }

    public List<Errors> errors;
    public List<LocationGroups> locationGroups;
    public List<Locations> locations;
    public Boolean success;

    public class LocationGroups {
        public List<InventoryRecords> inventoryRecords;
        public String locationGroupIdentifier;
    }

    public class InventoryRecords {
        public Double availableToFulfill;
        public Double availableToOrder;
        public String effectiveDate;
        public List<Errors> futures;
        public Double onHand;
        public Double reserved;
        public Double safetyStockCount;
        public String stockKeepingUnit;
    }

    public class Locations {
        public List<InventoryRecords> inventoryRecords;
        public String locationIdentifier;
    }

    
    public static WrapperClass parse(String json) {
        return (WrapperClass) System.JSON.deserialize(json, WrapperClass.class);
    }*/
}